//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HookshotDll.rc
//
#define IDS_HOOKSHOT_VERSION_NAME       101
#define IDS_HOOKSHOT_ERROR_INJECT_FAILED_FORMAT 102
#define IDS_HOOKSHOT_SUCCESS_INJECT_FORMAT 103
#define IDS_HOOKSHOT_DEBUG_PID_FORMAT   104
#define IDS_HOOKSHOT_WARN_CANNOT_LOAD_HOOK_MODULE_FORMAT 105
#define IDS_HOOKSHOT_INFO_ATTEMPT_LOAD_HOOK_MODULE_FORMAT 106
#define IDS_HOOKSHOT_WARN_MALFORMED_HOOKSHOT_MODULE_FORMAT 107
#define IDS_HOOKSHOT_INFO_HOOK_MODULE_SUCCESS_FORMAT 108
#define IDS_HOOKSHOT_WARN_NO_HOOK_MODULE 109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
